### PR TITLE
Use cross-platform crates for page boundary tests

### LINKED ISSUE #29: Tests don't compile on Windows
Trying to run tests on Windows fails with following compilation errors:

```
error[E0425]: cannot find value `MAP_ANONYMOUS` in module `libc`
   --> src\simd.rs:668:48
    |
668 |     const MAP_ANONYMOUS: libc::int32_t = libc::MAP_ANONYMOUS;
    |                                                ^^^^^^^^^^^^^ not found in `libc`
help: possible candidate is found in another module, you can import it into scope
    |
298 |     use simd::test::MAP_ANONYMOUS;
    |

error[E0425]: cannot find value `PROT_READ` in module `libc`
   --> src\simd.rs:684:30
    |
684 |             let prot = libc::PROT_READ | libc::PROT_WRITE;
    |                              ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_WRITE` in module `libc`
   --> src\simd.rs:684:48
    |
684 |             let prot = libc::PROT_READ | libc::PROT_WRITE;
    |                                                ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `MAP_PRIVATE` in module `libc`
   --> src\simd.rs:685:31
    |
685 |             let flags = libc::MAP_PRIVATE | MAP_ANONYMOUS;
    |                               ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `mmap` in module `libc`
   --> src\simd.rs:689:36
    |
689 |             let first_page = libc::mmap(addr, length, prot, flags, fd, offset);
    |                                    ^^^^ not found in `libc`

error[E0425]: cannot find value `PROT_NONE` in module `libc`
   --> src\simd.rs:699:34
    |
699 |                 let prot = libc::PROT_NONE;
    |                                  ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `mprotect` in module `libc`
   --> src\simd.rs:701:45
    |
701 |                 let mprotect_retval = libc::mprotect(addr, length, prot);
    |                                             ^^^^^^^^ not found in `libc`

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `jetscii`.

To learn more, run the command again with --verbose.
```

It would be better to use platform-independent crate like https://crates.io/crates/region.

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #29.

### CODE REVIEW

File: src/simd.rs [hunk 1]
```diff
@@ -661,52 +662,28 @@ mod test {
...
+        let (first_page, second_page) = mmap.split_at_mut(page_size);
 
-            // Copy bytes to the end of the first page
-            let start = second_page.offset(-(value.len() as isize)) as *mut u8;
-            ptr::copy_nonoverlapping(value.as_ptr(), start, value.len());
-            str::from_utf8_unchecked(slice::from_raw_parts(start, value.len()))
+        // Prohibit any access to the second page, so that any attempt
+        // to read or write it would trigger a segfault
+        unsafe {
+            region::protect(second_page.as_ptr(), page_size, Protection::None).unwrap();
```
Comment (shepmaster) [inline src/simd.rs:680]: That's an unfortunate choice of variant name. It sounds like there's *no protection*

File: src/simd.rs [hunk 2]
```diff
@@ -721,17 +698,17 @@ mod test {
 
         // Allocate a 16-byte string at page boundary.  To verify this
         // test, set protect=false to prevent segfaults.
-        let text = alloc_guarded_string("0123456789abcdef", true);
```
Comment (shepmaster) [inline src/simd.rs:724]: While seemingly silly, the boolean parameter allowed for quickly checking to ensure that the test would appropriately fail. You can see this in the (now-outdated) comment directly above the call. Can this be restored in some fashion?

Comment (shepmaster) [reply src/simd.rs:724]: And check to make sure that the test behavior flips when appropriate 😄

**Comment by shepmaster** [comment]
Thanks! I suppose I should take the time to set up Windows-based CI as well...

**Comment by RReverser** [comment]
@shepmaster Well, these days it should be as easy as adding another line to travis.yml :) https://blog.travis-ci.com/2018-10-11-windows-early-release (although not 100% sure if they have Rust packaged there yet).

File: src/simd.rs (hunk 2 above)
Comment (RReverser) [reply src/simd.rs:724]: Hmm... it didn't seem to be ever used?

File: src/simd.rs (hunk 1 above)
Comment (RReverser) [reply src/simd.rs:680]: Heh, I guess. Although it does correspond to the name of constant in libc (`PROT_NONE`).

File: src/simd.rs (hunk 2 above)
Comment (RReverser) [reply src/simd.rs:724]: Ping.

Comment (shepmaster) [reply src/simd.rs:724]: Right. It's a manual flip at the moment. Causing the test to fail usually results in a segfault, which can't be caught by the test harness, so it's not possible to write a test that asserts the bad behavior.

Comment (RReverser) [reply src/simd.rs:724]: Right, but it used to always `protect`, so are you saying you used to manually disable protection? I don't see how it would make a test fail, rather the opposite.

I'm happy to reintroduce the flag, just trying to figure out in which case you *wouldn't* want the protection to be applied.

Comment (shepmaster) [reply src/simd.rs:724]: > so are you saying you used to manually disable protection

Yes, that's what I meant.

Honestly, I don't fully recall when I wanted to turn it off (you can see it was there from the very first PR #1), so I'm ok with waiting until I remember and then re-adding it.

**Review by shepmaster — APPROVED** [review]
Thanks for bearing with me over the holidays!
